services:
  db:
    container_name: db
    image: kapua/kapua-sql:${IMAGE_VERSION}
    ports:
      - "3307:3306"
  es:
    container_name: es
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.1
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - cluster.name=kapua-datastore
      - discovery.type=single-node
      - transport.host=_site_
      - transport.ping_schedule=-1
      - transport.tcp.connect_timeout=30s
  events-broker:
    container_name: events-broker
    image: kapua/kapua-events-broker:${IMAGE_VERSION}
    ports:
      - "5672:5672"
  broker:
    container_name: broker
    image: kapua/kapua-broker:${IMAGE_VERSION}
    expose:
      - 1893
    ports:
      - "1883:1883"
      - "8883:8883"
      - "52614:61614"
    depends_on:
      - db
      - es
      - events-broker
    environment:
      - CRYPTO_SECRET_KEY
      - KAPUA_DISABLE_SSL
      - KAPUA_DISABLE_DATASTORE
      - KAPUA_CRT
      - KAPUA_CA
      - KAPUA_KEY
      - KAPUA_KEY_PASSWORD
      - KAPUA_KEYSTORE
      - KAPUA_KEYSTORE_PASSWORD
      - LOGBACK_LOG_LEVEL
  kapua-console:
    container_name: kapua-console
    image: kapua/kapua-console:${IMAGE_VERSION}
    ports:
      - "8083:8080"
      - "8445:8443"
    depends_on:
      - broker
      - db
      - es
      - events-broker
    environment:
      - CRYPTO_SECRET_KEY
      - KAPUA_DISABLE_SSL
      - KAPUA_DISABLE_DATASTORE
      - KAPUA_CA
      - KAPUA_CRT
      - KAPUA_KEY
      - KAPUA_KEY_PASSWORD
      - KAPUA_KEYSTORE
      - KAPUA_KEYSTORE_PASSWORD
      - LOGBACK_LOG_LEVEL
      - KAPUA_CONSOLE_URL=http://localhost:8083
      - KAPUA_OPENID_JWT_ISSUER=https://accounts.google.com
      - KAPUA_OPENID_CLIENT_ID
      - KAPUA_OPENID_CLIENT_SECRET
      - KAPUA_OPENID_JWT_AUDIENCE
      - KAPUA_OPENID_AUTH_ENDPOINT=https://accounts.google.com/o/oauth2/v2/auth
      - KAPUA_OPENID_TOKEN_ENDPOINT=https://oauth2.googleapis.com/token
      - KAPUA_OPENID_LOGOUT_ENDPOINT=https://oauth2.googleapis.com/revoke
      - KAPUA_OPENID_USERINFO_ENDPOINT=https://www.googleapis.com/oauth2/v3/userinfo
      - JETTY_DEBUG_OPTS=-Dauthentication.registration.service.enabled=true -Dconsole.sso.openid.user.logout.enabled=false -Dsso.openid.claims.externalUsername.key=email -Dauto.registration.simple.accountExpirationDate.days=0 -Dauto.registration.simple.maximumNumberOfChildUsers=2 -Dconsole.sso.openid.redirect.uri=https://localhost/openid/callback
  kapua-api:
    container_name: kapua-api
    image: kapua/kapua-api:${IMAGE_VERSION}
    expose:
      - "8080"
      - "8443"
    depends_on:
      - broker
      - db
      - es
      - events-broker
    environment:
      - API_CORS_ORIGINS_ALLOWED
      - CRYPTO_SECRET_KEY
      - KAPUA_DISABLE_SSL
      - KAPUA_DISABLE_DATASTORE
      - KAPUA_CA
      - KAPUA_CRT
      - KAPUA_KEY
      - KAPUA_KEY_PASSWORD
      - KAPUA_KEYSTORE
      - KAPUA_KEYSTORE_PASSWORD
      - LOGBACK_LOG_LEVEL
      - SWAGGER=${KAPUA_SWAGGER_ENABLE:-true}
      - BROKER_ADDR=172.16.19.37
      - JETTY_DEBUG_OPTS=-Dauthentication.registration.service.enabled=true -Dbroker.scheme=tcp -Dbroker.mqtt.password=kapua-password -Dsso.openid.provider=generic -Dsso.openid.client.id=${KAPUA_OPENID_CLIENT_ID} -Dsso.openid.client.secret=${KAPUA_OPENID_CLIENT_SECRET} -Dsso.openid.generic.jwt.issuer.allowed=https://accounts.google.com -Dsso.openid.generic.jwt.audience.allowed=${KAPUA_OPENID_JWT_AUDIENCE} -Dsso.openid.generic.server.endpoint.auth=https://accounts.google.com/o/oauth2/v2/auth -Dsso.openid.generic.server.endpoint.token=https://oauth2.googleapis.com/token -Dsso.openid.generic.server.endpoint.userinfo=https://www.googleapis.com/oauth2/v3/userinfo -Dsso.openid.claims.externalUsername.key=email
  job-engine:
    container_name: job-engine
    image: kapua/kapua-job-engine:${IMAGE_VERSION}
    expose:
      - 8080
    depends_on:
      - broker
      - db
      - events-broker
    environment:
      - CRYPTO_SECRET_KEY
      - KAPUA_DISABLE_SSL
      - KAPUA_DISABLE_DATASTORE
      - KAPUA_CA
      - KAPUA_CRT
      - KAPUA_KEY
      - KAPUA_KEY_PASSWORD
      - KAPUA_KEYSTORE
      - KAPUA_KEYSTORE_PASSWORD
      - LOGBACK_LOG_LEVEL
